### ISSUE TITLE
Verify the app on Flathub

### ISSUE THREAD

**Issue by RaptaG** [flathub/io.vikunja.Vikunja#18]
@kolaente it would be awesome if we could verify the app on Flathub! The instructions are here:

https://flathub.org/about

**Comment by kolaente** [comment]
I've verified the app, but it still shows up as unverified on https://flathub.org/apps/io.vikunja.Vikunja. I guess it will take a while for the status to propagate.

**Comment by RaptaG** [comment]
It shows up now, awesome!
