### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by spoorun** [flathub/io.vikunja.Vikunja#4]
The Vikunja flatpak is not configured to support Wayland (which is now becoming default in many systems).
Instead, when run in a Wayland enviroment, the flatpak still runs in XWayland.

Suggested:
a) It should run in Wayland and fall back to X (as many flatpaks now do)
b) Care should be taken to ensure the icon displays in Wayland (ensuring the correct 'appid' is set and it matches the first part of the .desktop file name.

**Comment by kolaente** [comment]
Do you want to send a PR?

**Comment by RaptaG** [comment]
I'll do my best to get this done! I quite forgot about it because I made the PR on my laptop (running X), but on my main desktop I use Wayland too!

**Comment by RaptaG** [comment]
Fixed as of https://github.com/flathub/io.vikunja.Vikunja/commit/b3bb74e2683ad8490b617611d877b87b96dab885
